# Makefile for compiling the Tk plugin on Win32 platforms with VC++ 4.0
# and later.
#
# CONTACT:		sunscript-plugin@sunscript.sun.com
#
# AUTHORS:		Jacob Levy			Laurent Demailly
#			jyl@eng.sun.com			demailly@eng.sun.com
#			jyl@tcl-tk.com			L@demailly.com
#
# Please contact us directly for questions, comments and enhancements.
#
# Copyright (c) 1996-1997 Sun Microsystems, Inc.
# Copyright (c) 2000 by Scriptics Corporation.
#
# See the file "license.terms" for information on usage and redistribution
# of this file, and for a DISCLAIMER OF ALL WARRANTIES.
#
# SCCS: @(#) makefile.vc 1.21 97/12/02 15:45:35
# RCS:  @(#) $Id$

ROOT	= ..
TMPDIR	= .
OUTDIR	= $(TMPDIR)
TOOLS32	= c:\progra~1\devstu~1\Vc
TOOLS32RC	= c:\progra~1\devstu~1\SharedIDE
TK	= ..\..\tk8.3.1
TCL	= ..\..\tcl8.3.1

MACHINE	= IX86

# Figure out which configuration is being built.

!IF "$(CFG)" == ""
CFG=nptcl32 - Win32 Debug
!MESSAGE No configuration specified. Defaulting to nptcl32 - Win32 Release.
!ENDIF

# If the configuration is not one we know, die with a nice error message.

!IF "$(CFG)" != "nptcl32 - Win32 Release" && \
	"$(CFG)" != "nptcl32 - Win32 Debug"
!MESSAGE Invalid configuration "$(CFG)" specified.
!MESSAGE You can specify a configuration when running NMAKE on this makefile
!MESSAGE by defining the macro CFG on the command line.  For example:
!MESSAGE 
!MESSAGE NMAKE /f "makefile.vc" CFG="nptcl32 - Win32 Debug"
!MESSAGE 
!MESSAGE Possible choices for configuration are:
!MESSAGE 
!MESSAGE "nptcl32 - Win32 Release" (based on "Win32 (x86) DLL")
!MESSAGE "nptcl32 - Win32 Debug" (based on "Win32 (x86) DLL")
!MESSAGE 
!ERROR An invalid configuration is specified.
!ENDIF

!IF "$(CFG)" == "nptcl32 - Win32 Release"
NODEBUG=1
!ENDIF

# Make sure the VC++ tools are at the head of the path
PATH=$(TOOLS32)\bin;$(PATH)

cc32 = $(TOOLS32)\bin\cl -I$(TOOLS32)\include
rc32 = $(TOOLS32RC)\bin\rc
link32 = $(TOOLS32)\bin\link

INCLUDES= -I. -I$(ROOT)\generic -I$(TCL)\generic -I$(TK)\generic \
	  -I$(TK)\xlib -I$(TK)\xlib -I$(TK)\win

OBJS = \
	$(OUTDIR)\tclMiscUtils.obj \
	$(OUTDIR)\nptcl.obj \
	$(OUTDIR)\npinterp.obj \
	$(OUTDIR)\nptoken.obj \
	$(OUTDIR)\npcmd.obj \
	$(OUTDIR)\nplog.obj \
	$(OUTDIR)\npwin.obj \
	$(OUTDIR)\npstream.obj \
	$(OUTDIR)\npwinplatform.obj \
	$(OUTDIR)\npwindll.obj \
	$(OUTDIR)\npdll32.res

######################################################################
# Link flags
######################################################################

!IFDEF NODEBUG
ldebug = /RELEASE
!ELSE
ldebug = -debug:full -debugtype:cv
!ENDIF

# declarations common to all linker options
lcommon = /NODEFAULTLIB /RELEASE /NOLOGO

# declarations for use on Intel i386, i486, and Pentium systems
!IF "$(MACHINE)" == "IX86"
DLLENTRY = @12
lflags   = $(lcommon) -align:0x1000 /MACHINE:$(MACHINE)
!ELSE
lflags   = $(lcommon) /MACHINE:$(MACHINE)
!ENDIF

conlflags = $(lflags) -subsystem:console -entry:mainCRTStartup
guilflags = $(lflags) -subsystem:windows -entry:WinMainCRTStartup
dlllflags = $(lflags) -entry:_DllMainCRTStartup$(DLLENTRY) -dll

!IF "$(MACHINE)" == "PPC"
libcdll = crtdll.lib
!ELSE
libcdll = msvcrt.lib oldnames.lib
!ENDIF

baselibs   = kernel32.lib $(optlibs) advapi32.lib
winlibs    = $(baselibs) user32.lib gdi32.lib comdlg32.lib winspool.lib

guilibsdll = $(libcdll) $(winlibs)

######################################################################
# Compile flags
######################################################################

!IFDEF NODEBUG
cdebug = -Ox
!ELSE
cdebug = -Z7 -Od
!ENDIF

# declarations common to all compiler options
ccommon = -c -W3 -Dtry=__try -Dexcept=__except -Dleave=__leave \
	  -Dfinally=__finally -DCRTAPI1=_cdecl -DCRTAPI2=_cdecl \
	  -nologo -D_WINDOWS -DUSE_TCL_STUBS -DUSE_TK_STUBS -DSTATIC_BUILD

!IF "$(MACHINE)" == "IX86"
cflags = $(ccommon) -D_X86_=1 $(IE_30_FLAGS) -DXP_WIN32
!ELSE
!IF "$(MACHINE)" == "MIPS"
cflags = $(ccommon) -D_MIPS_=1
!ELSE
!IF "$(MACHINE)" == "PPC"
cflags = $(ccommon) -D_PPC_=1
!ELSE
!IF "$(MACHINE)" == "ALPHA"
cflags = $(ccommon) -D_ALPHA_=1
!ENDIF
!ENDIF
!ENDIF
!ENDIF

cvars      = -DWIN32 -D_WIN32
cvarsmt    = $(cvars) -D_MT
cvarsdll   = $(cvarsmt) -D_DLL

######################################################################
# Project specific targets
######################################################################

TCLVERSION = 83
DEF_FILE= npdll32.def

# Flags for the linker:

LFLAGS	= $(LDEBUG) $(LLIBS) $(LCOMMON) $(LOBJS)
LLIBS	= $(TCL)\win\Release\tcl$(TCLVERSION).lib $(TK)\win\Release\tk$(TCLVERSION).lib \
	msvcrt.lib oldnames.lib kernel32.lib user32.lib advapi32.lib



# Additional targets for the external wish

WISH = wish$(TCLVERSION).exe

TKBUILD= $(TK)\win

WISHOBJS = \
	$(TKBUILD)\Release\tkConsole.obj \
	$(TMPDIR)\plugWinMain.obj

WISH = wish$(TCLVERSION).exe

# Main target:

all: $(OUTDIR)\nptcl32.dll $(WISH)

$(OUTDIR)\nptcl32.dll: $(DEF_FILE) $(OBJS)
	$(link32) $(ldebug) $(dlllflags) -def:$(DEF_FILE) \
		$(TCL)\win\Release\tclstub$(TCLVERSION).lib \
		$(guilibsdll) -out:$(OUTDIR)\nptcl32.dll @<<
		$(OBJS)
<<

{$(ROOT)\generic}.c{$(TMPDIR)}.obj:
	$(cc32) $(cdebug) $(cflags) $(cvarsdll) $(INCLUDES) \
		-Fo$(TMPDIR)\ $<

{$(ROOT)\win}.c{$(TMPDIR)}.obj:
	$(cc32) $(cdebug) $(cflags) $(cvarsdll) $(INCLUDES) \
		-Fo$(TMPDIR)\ $<

{$(ROOT)\win}.cpp{$(TMPDIR)}.obj:
	$(cc32) $(cdebug) $(cflags) $(cvarsdll) $(INCLUDES) \
		-Fo$(TMPDIR)\ $<

{$(ROOT)\win}.rc{$(TMPDIR)}.res:
	$(rc32) -fo $@ -r -i $(ROOT)\generic $<

# Cleaning up:

clean:
	-@erase "$(OUTDIR)\npdll32.res"
	-@erase "$(OUTDIR)\*.obj"
	-@erase "$(OUTDIR)\nptcl32.pdb"
	-@erase "$(OUTDIR)\nptcl32.dll"
	-@erase "$(OUTDIR)\nptcl32.exp"
	-@erase "$(OUTDIR)\nptcl32.lib"

# Build target for wish

$(WISH): $(OUTDIR)\nptcl32.lib $(WISHOBJS) $(TKBUILD)\rc\wish.res
	set LIB=$(TOOLS32)\lib
	$(link32) $(ldebug) $(guilflags) $(TKBUILD)\rc\wish.res -out:$@ \
		$(guilibsdll) $(WISHOBJS) \
		$(TCL)\win\Release\tcl$(TCLVERSION).lib \
		$(TK)\win\Release\tk$(TCLVERSION).lib \
		$(OUTDIR)\nptcl32.lib
