dnl 		Process this file with autoconf to produce a configure script.

#	configure script to create a fat (containing tcl+tk) version
#	of the tclplugin  -- dl

AC_INIT(../generic/nptcl.c)
AC_CONFIG_HEADER(npconfig.h)

# SCCS: @(#) configure.in 1.34 98/01/13 17:42:58
# RCS:  @(#) $Id$

##### Section that needs to be updated for each new release ######

NPTCL_MAJOR_VERSION=2
NPTCL_MINOR_VERSION=1
# Like for Tcl and Tk :
# The release level (quality) : 0 for alpha, 1 for beta, and 2 for
# final/patch.  The release serial value is the number that follows the
# "a", "b", or "p" in the patch level; for example, if the patch level
# is 2.1b2, NPTCL_RELEASE_SERIAL is 2.  It restarts at 1 whenever the
# release level is changed, except for the final release which is 0
# (the first patch will start at 1).
NPTCL_RELEASE_LEVEL=1
NPTCL_RELEASE_SERIAL=1

# nb: don't forget to update win/npconfig.h and mac/npconfig.h to reflect
#     the version strings produced by this configure script in npconfig.h
#     (a sed/shell/tcl script to do that might be a nice addition, when
#      time will permit)
#     Likewise, win/res/npdll32.rc2 and win/plugin.wse needs to be updated too
#     and mac/npMacResource.r
#     (script or configure will be done when time permit too)


TCLTK_EXPECTED_VERSION=8.3.1
AC_SUBST(TCLTK_EXPECTED_VERSION)

# The patch level is computed automatically below. no changes should be needed.

##### End of Section that needs to be updated for each new release ######

NPTCL_VERSION=$NPTCL_MAJOR_VERSION.$NPTCL_MINOR_VERSION

if test $NPTCL_RELEASE_LEVEL -eq 0; then
   NPTCL_RELEASE_SUFFIX=a$NPTCL_RELEASE_SERIAL
elif test $NPTCL_RELEASE_LEVEL -eq 1; then
   NPTCL_RELEASE_SUFFIX=b$NPTCL_RELEASE_SERIAL
elif test $NPTCL_RELEASE_LEVEL -eq 2; then
   if test $NPTCL_RELEASE_SERIAL -eq 0; then
	NPTCL_RELEASE_SUFFIX=""
   else
        NPTCL_RELEASE_SUFFIX=.$NPTCL_RELEASE_SERIAL
   fi
else
   AC_MSG_ERROR(Invalid release level '$NPTCL_RELEASE_LEVEL')
fi

NPTCL_PATCH_LEVEL=$NPTCL_VERSION$NPTCL_RELEASE_SUFFIX

NPTCL_DISTRIB_NAME=$NPTCL_MAJOR_VERSION$NPTCL_MINOR_VERSION$NPTCL_RELEASE_SUFFIX
# 3 digits version (package version):

NPTCL_INTERNAL_VERSION=$NPTCL_VERSION.`expr $NPTCL_RELEASE_LEVEL \* 100 + $NPTCL_RELEASE_SERIAL`

VERSION=${NPTCL_VERSION}
AC_SUBST(NPTCL_VERSION)
AC_SUBST(NPTCL_MAJOR_VERSION)
AC_SUBST(NPTCL_MINOR_VERSION)
AC_SUBST(NPTCL_PATCH_LEVEL)
AC_SUBST(NPTCL_RELEASE_LEVEL)
AC_SUBST(NPTCL_RELEASE_SERIAL)
AC_SUBST(NPTCL_INTERNAL_VERSION)
AC_SUBST(NPTCL_DISTRIB_NAME)

AC_SUBST(VERSION)

# Real absolute topdir :
TOP_DIR=`cd $srcdir/..;pwd`
AC_SUBST(TOP_DIR)


#		Check for configure command line options

#	PLUGIN_TRACE option
AC_ARG_ENABLE(plugin-trace,[  --enable-plugin-trace   Enable Plugin Trace (debug output)],,enableval="no")

if test "$enableval" = "yes"; then
  AC_DEFINE(PLUGIN_TRACE)
  AC_MSG_RESULT(Will compile with Plugin Trace)
else
  AC_MSG_RESULT(Will compile without Plugin Trace (normal))
fi

AC_MSG_CHECKING(Mozilla Home)
# Check for Mozilla home (install directory of netscape (plugins))
AC_ARG_WITH(mozilla, [  --with-mozilla=DIR      Will install in DIR/plugins and DIR/tclplug],
	MOZILLA_DIR=$withval, MOZILLA_DIR="$MOZILLA_HOME")

if test -z "$MOZILLA_DIR"; then
	MOZILLA_DIR=/usr/local/lib/netscape
fi

if test ! -d "$MOZILLA_DIR"; then
    AC_MSG_ERROR(Mozilla home directory \"$MOZILLA_DIR\" doesn't exist: use configure --with-mozilla=MOZILLA_HOME - ie. --with-mozilla=$HOME/.netscape for a personal install)
fi
AC_MSG_RESULT(found. will install in \"$MOZILLA_DIR\")

AC_SUBST(MOZILLA_DIR)

# Check for Tcl and Tk *build* directories
AC_ARG_WITH(tcl, [  --with-tcl=DIR          use Tcl 8.3.1 build dir from DIR],
	TCL_BIN_DIR=$withval, TCL_BIN_DIR="$srcdir/../../tcl8.3.1/unix")
if test ! -d $TCL_BIN_DIR; then
    AC_MSG_ERROR(Tcl directory $TCL_BIN_DIR doesn't exist: use configure --with-tcl=TCL_BUILD_DIR)
fi
TCL_BIN_DIR=`cd $TCL_BIN_DIR;pwd`
if test ! -f $TCL_BIN_DIR/Makefile; then
    AC_MSG_ERROR(There's no Makefile in $TCL_BIN_DIR;  perhaps you didn't specify the Tcl *build* directory (not the toplevel Tcl directory) or you forgot to configure Tcl?)
fi

AC_ARG_WITH(tk, [  --with-tk=DIR           use Tk 8.3.1 build dir from DIR],
	TK_BIN_DIR=$withval, TK_BIN_DIR="$srcdir/../../tk8.3.1/unix")
if test ! -d $TK_BIN_DIR; then
    AC_MSG_ERROR(Tk directory $TK_BIN_DIR doesn't exist: use configure --with-tk=TK_BUILD_DIR)
fi
TK_BIN_DIR=`cd $TK_BIN_DIR; pwd`
if test ! -f $TK_BIN_DIR/Makefile; then
    AC_MSG_ERROR(There's no Makefile in $TK_BIN_DIR;  perhaps you didn't specify the Tk *build* directory (not the toplevel Tk directory) or you forgot to configure Tk?)
fi

#	Read in configuration information generated by Tcl for shared
#	libraries, and arrange for it to be substituted into our
#	Makefile.

AC_MSG_CHECKING(tclConfig.sh)
file=$TCL_BIN_DIR/tclConfig.sh
. $file
AC_MSG_RESULT(read ok)


# Check that Tcl is new enough for the plugin APIs used here.
AC_MSG_CHECKING(Tcl version and patch level)
FV="${TCL_PATCH_LEVEL}"
case "${TCL_VERSION}" in
    8.[[3-9]]|[[9-9]].*) ;;
    *) AC_MSG_ERROR(Tcl 8.3 or newer is required - found '${FV}') ;;
esac
if test -z "${FV}"; then
	AC_MSG_ERROR(Could not determine the Tcl patch level)
fi
AC_MSG_RESULT(${FV} - ok)


AC_MSG_CHECKING(tkConfig.sh)
file=$TK_BIN_DIR/tkConfig.sh
. $file
AC_MSG_RESULT(read ok)


# Check that Tcl and Tk have the same major and minor version.
AC_MSG_CHECKING(Tk version and patch level)
FV="${TK_PATCH_LEVEL}"
if test "${TK_VERSION}" != "${TCL_VERSION}" ; then
	AC_MSG_ERROR(Tcl/Tk version mismatch: Tcl '${TCL_VERSION}', Tk '${TK_VERSION}')
fi
AC_MSG_RESULT(${FV} - ok)



SHLIB_CFLAGS=$TCL_SHLIB_CFLAGS
SHLIB_LD=$TCL_SHLIB_LD
SHLIB_LD_LIBS=$TCL_SHLIB_LD_LIBS
SHLIB_SUFFIX=$TCL_SHLIB_SUFFIX
# we need to evaluate that one
eval "NSP_LIB_FILE=libtclp${TCL_SHARED_LIB_SUFFIX}"
AC_SUBST(NSP_LIB_FILE)

CC=$TCL_CC
RANLIB=$TCL_RANLIB

AC_SUBST(TCL_BIN_DIR)
AC_SUBST(TK_BIN_DIR)
AC_SUBST(POW_BIN_DIR)
AC_SUBST(FITSTCL_BIN_DIR)
AC_SUBST(CFITSIO_BIN_DIR)

AC_SUBST(CC)
AC_SUBST(RANLIB)
AC_SUBST(SHLIB_CFLAGS)
AC_SUBST(SHLIB_LD)
AC_SUBST(SHLIB_LD_LIBS)
AC_SUBST(SHLIB_SUFFIX)
AC_SUBST(TCL_LIB_SPEC)
AC_SUBST(TCL_LIBS)
AC_SUBST(TCL_VERSION)
AC_SUBST(TCL_EXEC_PREFIX)
AC_SUBST(TCL_PREFIX)
AC_SUBST(TCL_SRC_DIR)
AC_SUBST(TCL_LD_SEARCH_FLAGS)
AC_SUBST(TCL_SHARED_LIB_SUFFIX)
AC_SUBST(SHARED_LIB_SUFFIX)
AC_SUBST(TCL_DEFS)

AC_SUBST(TK_VERSION)
AC_SUBST(TK_XINCLUDES)
AC_SUBST(TK_SRC_DIR)
AC_SUBST(TK_LIBS)
AC_SUBST(TCL_SHLIB_LD_LIBS)
AC_SUBST(TK_LD_SEARCH_FLAGS)

# Check that --enable-shared has been used for both tcl and tk
if test "$TCL_SHARED_BUILD" != "1"; then
	AC_MSG_ERROR(You need to configure tcl with --enable-shared and rebuild to build the plugin)
fi
if test "$TK_SHARED_BUILD" != "1"; then
	AC_MSG_ERROR(You need to configure tk with --enable-shared and rebuild to build the plugin)
fi

# compute the -L/-l flags that will be needed to create the tclshp
if test "${TCL_LIB_VERSIONS_OK}" = "ok"; then
    BUILD_LIB_SPEC="-L`pwd` -ltclp${VERSION}"
else
    BUILD_LIB_SPEC="-L`pwd` -ltclp`echo ${VERSION} | tr -d .`"
fi
AC_SUBST(BUILD_LIB_SPEC)

# We need ln -s
AC_PROG_LN_S

# Because the path was too long on some OS
# we need to ln the build dirs to make the paths shorter
AC_MSG_CHECKING(tclLibObjs)
# (before we were using the fullpath... not very nice either)
TCL_OBJECTS=""
# tail -1 is needed because the makefile there could rebuild itself before
# executing our empty target!
# We filter away the tclUnixNotfy.o because we have our own
# notifier
# We also filter out things in the tcl/tk core that we had to fix 
# and haven't yet made their way back into the core...
for obj in `(cd $TCL_BIN_DIR; make tclLibObjs|tail -1)` ; do
		TCL_OBJECTS="$TCL_OBJECTS \$(TCLBINDIR)/$obj"
done
AC_MSG_RESULT(ok)
AC_SUBST(TCL_OBJECTS)
AC_SUBST(TCL_LIB_FILE)

AC_MSG_CHECKING(tkLibObjs)
for obj in `(cd $TK_BIN_DIR; make tkLibObjs|tail -1)` ; do
		TK_OBJECTS="$TK_OBJECTS \$(TKBINDIR)/$obj"
done
AC_MSG_RESULT(ok)
AC_SUBST(TK_OBJECTS)

# Checks for programs.
AC_PROG_INSTALL
AC_PROG_CC

if test "$GCC" = "yes"; then
	CDEBUGFLAGS="-O2 -Wall -Wtraditional -Wmissing-prototypes -Wmissing-declarations -Wconversion -ansi -pedantic"
else
	CDEBUGFLAGS="-O"
fi
AC_SUBST(CDEBUGFLAGS)

# Checks for libraries.

# Checks for header files.
AC_CHECK_HEADERS(unistd.h)

# Checks for typedefs, structures, and compiler characteristics.
AC_C_CONST

# Checks for library functions.

AC_OUTPUT(Makefile npconfig.post, cat npconfig.post >> npconfig.h)
