#! /bin/bash -norc
#
# RCS: @(#) $Id$
#
#	configure script for nptcl

# Reflect version changes in:
#	generic/np.h   (any version)
#	win/npdll32.rc (major.minor only)
AC_INIT([nptcl], [3.1])
AC_DEFINE(PACKAGE_PATCHLEVEL, ["3.1.0"])

AC_CONFIG_AUX_DIR(tclconfig)

#--------------------------------------------------------------------
# Call TEA_INIT as the first TEA_ macro to set up initial vars.
# This will define a ${TEA_PLATFORM} variable == "unix" or "windows".
#--------------------------------------------------------------------

TEA_INIT([3.5])

AC_CONFIG_AUX_DIR(tclconfig)

TEA_PATH_TCLCONFIG
TEA_LOAD_TCLCONFIG
TEA_PATH_TKCONFIG
TEA_LOAD_TKCONFIG

TEA_PREFIX

TCLPLUGIN_MOZILLA_DIR
TCLPLUGIN_TRACE
TCLPLUGIN_LOG

TEA_SETUP_COMPILER

TEA_ADD_SOURCES([])
TEA_ADD_HEADERS([])
TEA_ADD_INCLUDES([-I. -I\"$(${CYGPATH} ${srcdir}/generic)\"])
TEA_ADD_LIBS([])
TEA_ADD_CFLAGS([])
TEA_ADD_STUB_SOURCES([])
TEA_ADD_TCL_SOURCES([])

AC_CHECK_SIZEOF(short)
AC_CHECK_SIZEOF(int)
AC_CHECK_SIZEOF(long)

TEA_ENABLE_THREADS

TEA_ENABLE_SHARED

TEA_CONFIG_CFLAGS

TEA_ENABLE_SYMBOLS

TEA_PUBLIC_TCL_HEADERS

AC_DEFUN([NP_CHECK_DLADDR], [
    # Check for the dladdr function
    # don't use AC_CHECK_LIB as that may not catch the _GNU_SOURCE requirement
    AC_CHECK_FUNC(dladdr, [AC_DEFINE(HAVE_DLADDR)],
	[AC_MSG_CHECKING([for dladdr via compilation])
AC_TRY_COMPILE([#define _GNU_SOURCE
#include <dlfcn.h>], [
	Dl_info info;
	dladdr("SHLIB_ID", &info);
], [AC_DEFINE(HAVE_DLADDR)
    AC_DEFINE(_GNU_SOURCE)
    AC_MSG_RESULT([found])],
	AC_MSG_RESULT([not found - no guaranteed dll-based kit support])
)])
])

if test "${TEA_PLATFORM}" != "windows" ; then
    # do this test before modifying CFLAGS
    NP_CHECK_DLADDR
fi

AC_DEFINE(USE_TCL_STUBS)

TEA_MAKE_LIB

CLEANFILES="pkgIndex.tcl install.js"
case "${TEA_WINDOWINGSYSTEM}" in
    win32)
	AC_DEFINE_UNQUOTED(BUILD_nptcl)
	CLEANFILES="${CLEANFILES} *.lib *.dll *.exp *.ilk *.pdb *.pch"
	TEA_ADD_SOURCES([\$(WIN_OBJECTS)])
	TEA_ADD_LIBS([advapi32.lib gdi32.lib user32.lib shlwapi.lib])
	AC_DEFINE(XP_WIN)
	AC_DEFINE(_WINDOWS)
	AC_DEFINE(_WIN32)
	AC_DEFINE(WIN32_LEAN_AND_MEAN)
	# We could do this with a .def file, but this is a bit easier
	# These functions need exporting, but they are part of the NPAPI that
	# has some strict declarations that you don't want to play with.
	SHLIB_LD="${SHLIB_LD} -export:NP_GetEntryPoints,@1"
	SHLIB_LD="${SHLIB_LD} -export:NP_Initialize,@2"
	SHLIB_LD="${SHLIB_LD} -export:NP_Shutdown,@3"
	LIB_RUNTIME_DIR=${TCL_EXEC_PREFIX}/bin
	TCL_LIB_FILE=${TCL_DLL_FILE}
	;;
    aqua)
	AC_DEFINE(XP_MACOSX)
	AC_DEFINE([MAC_TCL])
	AC_DEFINE([MAC_OSX_TCL])
	TEA_ADD_LIBS([-framework Carbon])
	TEA_ADD_SOURCES([\$(MACOSX_OBJECTS)])
	;;
    x11)
	AC_DEFINE(XP_UNIX)
	TEA_ADD_SOURCES([\$(UNIX_OBJECTS)])
	TCL_LIB_FILE=${TCL_LIB_FILE}
	# This should enable us to have the TCL_LIB_FILE located at runtime
	# with the -R path ... might not be necessary.
	LIB_RUNTIME_DIR=${TCL_EXEC_PREFIX}/lib
	SHLIB_LD="${SHLIB_LD} ${LD_SEARCH_FLAGS}"
	;;
    *)
	AC_MSG_ERROR([Unknown TEA_WINDOWINGSYSTEM "${TEA_WINDOWINGSYSTEM}"])
	;;
esac

AC_SUBST(LIB_RUNTIME_DIR)
AC_SUBST(TCL_LIB_FILE)
AC_SUBST(CLEANFILES)
AC_DEFINE_UNQUOTED(SHLIB_SUFFIX, "${SHLIB_SUFFIX}", [Tcl DLL extension suffix])

TEA_PROG_TCLSH
TEA_PROG_WISH

# Checks for library functions.

AC_OUTPUT([Makefile])
