#! /bin/bash -norc
#
# RCS: @(#) $Id$
#
#	configure script for nptcl

AC_INIT(generic/np.h)

AC_CONFIG_AUX_DIR(tclconfig)
CONFIGDIR=${srcdir}/tclconfig
AC_SUBST(CONFIGDIR)

PACKAGE=nptcl

##### Section that needs to be updated for each new release ######


# Reflect version changes in:
#	generic/np.h
#	win/res/npdll32.rc2
#	win/plugin.wse
#	mac/npMacResource.r

NPTCL_MAJOR_VERSION=3
NPTCL_MINOR_VERSION=0
# release level (quality): 0 for alpha, 1 for beta, and 2 for final/patch.
NPTCL_RELEASE_LEVEL=0
NPTCL_RELEASE_SERIAL=3
NPTCL_VERSION=$NPTCL_MAJOR_VERSION.$NPTCL_MINOR_VERSION
NPTCL_PATCH_LEVEL=${NPTCL_VERSION}a$NPTCL_RELEASE_SERIAL

##### End of Section that needs to be updated for each new release ######

# 3 digits version (package version):

NPTCL_INTERNAL_VERSION=$NPTCL_VERSION.`expr $NPTCL_RELEASE_LEVEL \* 100 + $NPTCL_RELEASE_SERIAL`

VERSION=${NPTCL_VERSION}
AC_SUBST(NPTCL_VERSION)
AC_SUBST(NPTCL_MAJOR_VERSION)
AC_SUBST(NPTCL_MINOR_VERSION)
AC_SUBST(NPTCL_PATCH_LEVEL)
AC_SUBST(NPTCL_RELEASE_LEVEL)
AC_SUBST(NPTCL_RELEASE_SERIAL)
AC_SUBST(NPTCL_INTERNAL_VERSION)

AC_SUBST(PACKAGE)
AC_SUBST(VERSION)
AC_SUBST(nptcl_LIB_FILE)

#--------------------------------------------------------------------
# Call TEA_INIT as the first TEA_ macro to set up initial vars.
# This will define a ${TEA_PLATFORM} variable == "unix" or "windows".
#--------------------------------------------------------------------

TEA_INIT

TEA_PATH_TCLCONFIG
TEA_LOAD_TCLCONFIG

TEA_PREFIX

TCLPLUGIN_MOZILLA_DIR
TCLPLUGIN_TRACE
TCLPLUGIN_LOG

TEA_SETUP_COMPILER

TEA_PUBLIC_TCL_HEADERS

AC_CHECK_SIZEOF(short)
AC_CHECK_SIZEOF(int)
AC_CHECK_SIZEOF(long)

# Checks for header files.
AC_CHECK_HEADERS(unistd.h)

# We need ln -s
AC_PROG_LN_S

if test "${TEA_PLATFORM}" = "windows" ; then
    AC_DEFINE_UNQUOTED(BUILD_nptcl)
    CLEANFILES="pkgIndex.tcl *.lib *.dll *.exp *.ilk *.pdb *.pch"
    EXTRA_OBJECTS='$(WIN_OBJECTS)'
    #EXTRA_OBJECTS='npdll32.res'
else
    CLEANFILES="pkgIndex.tcl"
    EXTRA_OBJECTS='$(UNIX_OBJECTS)'
fi

AC_SUBST(EXTRA_OBJECTS)
AC_SUBST(CLEANFILES)

TEA_ENABLE_THREADS

TEA_ENABLE_SHARED

TEA_CONFIG_CFLAGS

TEA_ENABLE_SYMBOLS

AC_DEFUN([NP_CHECK_DLADDR], [
    # Check for the dladdr function
    # don't use AC_CHECK_LIB as that may not catch the _GNU_SOURCE requirement
    AC_CHECK_FUNC(dladdr, [AC_DEFINE(HAVE_DLADDR)],
	[AC_MSG_CHECKING([for dladdr via compilation])
AC_TRY_COMPILE([#define _GNU_SOURCE
#include <dlfcn.h>], [
	Dl_info info;
	dladdr("SHLIB_ID", &info);
], [AC_DEFINE(HAVE_DLADDR)
    AC_DEFINE(_GNU_SOURCE)
    AC_MSG_RESULT([found])],
	AC_MSG_RESULT([not found - no guaranteed dll-based kit support])
)])
])

if test "${TEA_PLATFORM}" != "windows" ; then
    # do this test before modifying CFLAGS
    NP_CHECK_DLADDR
fi

if test "${SHARED_BUILD}" = "1" ; then
    CFLAGS='${CFLAGS_DEFAULT} ${CFLAGS_WARNING} ${SHLIB_CFLAGS}'
else
    CFLAGS='${CFLAGS_DEFAULT} ${CFLAGS_WARNING}'
fi

AC_DEFINE(USE_TCL_STUBS)

TEA_MAKE_LIB

if test "${TEA_PLATFORM}" = "windows" ; then
    AC_DEFINE(XP_WINDOWS)
    AC_DEFINE(XP_WIN32)
    AC_DEFINE(XP_WIN)
    AC_DEFINE(XP_PC)
    AC_DEFINE(_WINDOWS)
    AC_DEFINE(_WIN32)
    AC_DEFINE(WIN32)
    AC_DEFINE(_X86_)
    AC_DEFINE(WIN32_LEAN_AND_MEAN)
    LIBS="${LIBS} advapi32.lib gdi32.lib user32.lib"
    PLAT_DIR=
    SHLIB_LDFLAGS="${SHLIB_LDFLAGS} -def:\"`${CYGPATH} ${srcdir}/win`/npdll32.def\""
    LIB_RUNTIME_DIR=${TCL_EXEC_PREFIX}/bin
    TCL_LIB_FILE=${TCL_DLL_FILE}
else
    AC_DEFINE(XP_UNIX)
    LIB_RUNTIME_DIR=${TCL_EXEC_PREFIX}/lib
    TCL_LIB_FILE=${TCL_LIB_FILE}
    eval TCL_LD_SEARCH_FLAGS=${TCL_LD_SEARCH_FLAGS}
    SHLIB_LDFLAGS="${SHLIB_LDFLAGS} ${TCL_LD_SEARCH_FLAGS}"
fi
AC_SUBST(LIB_RUNTIME_DIR)
AC_SUBST(TCL_LIB_FILE)

TEA_PROG_TCLSH

# Checks for library functions.

AC_OUTPUT([Makefile])
